[package]
name = "pluto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "pluto"
path = "src/lib.rs"

[[bin]]
name = "pluto"
path = 'src/main.rs'

[[example]]
name = 'server'
